libgimp: fix typo and libgimpui build.
Apart from some obvious typo, libgimpui link was failing with meson
because it now relies on a function from libgimpconfig (i.e.
gimp_config_reset()), since commit 9d2d1fb917c [formerly bfb7f43dbcb]. This fixes:
> /usr/bin/ld: libgimp/gimpproceduredialog.c:223: undefined reference to `gimp_config_reset'


Former-commit-id: 396d227436f030fc3e6db8ca991783771a7fa1c5