plug-ins: replace s/printf/g_printf/
When cross-compiling, I got various linking errors for printf() calls:
> undefined reference to `libintl_printf'

I am unsure why, since this is not recent code, and it used to build
fine with mingw64 compilers (last I cross-built, which is many months
ago). Anyway g_printf() works fine, all necessary libs are already
linked, and it is supposed to be a synonym. So let's just go the easy
way and use g_printf() only.

(cherry picked from commit 0430c9400b552d54a537c3871c2a1e5ea15e39bd [formerly c49afa4f84c70538f7ed30784569bb4d32b159c0])


Former-commit-id: 0832bbd7713e785875b0ba1a061122289a97529a