tools: fix linking error.
Though no error was raised during a native build, a cross-build was
choking on this missing link to libgimpbase and failing.
The error returned by the linker though was a bit amiss.

Fixes:
> gimp-test-clipboard.o: In function `test_clipboard_copy_callback':
> tools/gimp-test-clipboard.c:419: undefined reference to `g_file_get_contents'
> collect2: error: ld returned 1 exit status

(cherry picked from commit 7cb22ab9fa9ef792ddec1a3d7eaee69aa03f7b6f [formerly 0865e9db1f27154816f5e01483a55fa6064fdbaa])


Former-commit-id: 14614969998557b36e2b70ede4e3bf902ec64ecd